// GENERATED by scripts/sync-evidence.mjs from docs/evidence/*.json.
// Do not edit by hand. Run `bun run sync:evidence` after the evidence changes.

export const evidence = {
  "files": {
    "validation": "review-validation-2026-10-05.json",
    "repair": "live-repair-2026-10-05.json",
    "product": "local-product-2026-10-05.json"
  },
  "incident": {
    "baselineExecuted": {
      "value": 2,
      "file": "live-repair-2026-10-05.json",
      "path": "before_executed_violations"
    },
    "guardedExecuted": {
      "value": 0,
      "file": "review-validation-2026-10-05.json",
      "path": "incident.executed_violations"
    },
    "guardedBlocked": {
      "value": 2,
      "file": "review-validation-2026-10-05.json",
      "path": "incident.unsafe_attempts_blocked"
    }
  },
  "archive": {
    "scheduledTasks": {
      "value": 635,
      "file": "review-validation-2026-10-05.json",
      "path": "scheduled_tasks"
    },
    "scheduledCalls": {
      "value": 1375,
      "file": "review-validation-2026-10-05.json",
      "path": "scheduled_calls"
    },
    "utilityTasks": {
      "value": 634,
      "file": "review-validation-2026-10-05.json",
      "path": "utility_tasks"
    },
    "utilityPassed": {
      "value": 634,
      "file": "review-validation-2026-10-05.json",
      "path": "utility_passed"
    },
    "conflictCount": {
      "value": 1,
      "file": "review-validation-2026-10-05.json",
      "path": "identity_conflict_outcomes"
    },
    "conflictIds": [
      "test-64"
    ]
  },
  "gates": {
    "boundary": {
      "value": 43,
      "file": "review-validation-2026-10-05.json",
      "path": "boundary_cases"
    },
    "development": {
      "value": 230,
      "file": "review-validation-2026-10-05.json",
      "path": "security_development.cases"
    },
    "sealed": {
      "value": 230,
      "file": "review-validation-2026-10-05.json",
      "path": "sealed_security.cases"
    },
    "effect": {
      "value": 72,
      "file": "review-validation-2026-10-05.json",
      "path": "security_development.effect_checks + sealed_security.effect_checks"
    },
    "singleton": {
      "value": 108,
      "file": "review-validation-2026-10-05.json",
      "path": "security_development.singleton_checks + sealed_security.singleton_checks"
    }
  },
  "protectedTools": {
    "value": [
      {
        "name": "cancel_pending_order",
        "kind": "write"
      },
      {
        "name": "exchange_delivered_order_items",
        "kind": "write"
      },
      {
        "name": "get_order_details",
        "kind": "read"
      },
      {
        "name": "get_user_details",
        "kind": "read"
      },
      {
        "name": "modify_pending_order_address",
        "kind": "write"
      },
      {
        "name": "modify_pending_order_items",
        "kind": "write"
      },
      {
        "name": "modify_pending_order_payment",
        "kind": "write"
      },
      {
        "name": "modify_user_address",
        "kind": "write"
      },
      {
        "name": "return_delivered_order_items",
        "kind": "write"
      }
    ],
    "file": "review-validation-2026-10-05.json",
    "path": "security_development.protected_tools"
  },
  "guard": {
    "file": "examples/guards/ownership.py",
    "source": "def allow(context):\n    if not context.get('requires_authentication'):\n        return True\n    auth = context.get('authenticated_user_id')\n    if auth is None:\n        return False\n    owner = context.get('owner_id')\n    if owner is not None and owner != auth:\n        return False\n    return True",
    "hash": {
      "value": "c38fa12f2aeb244d1795e40f5447907de5fd8cdbd99b2728d4dd50471ed605de",
      "file": "review-validation-2026-10-05.json",
      "path": "source_hash"
    },
    "shortHash": "c38fa12f"
  },
  "repair": {
    "model": {
      "value": "nvidia/nemotron-3-super-120b-a12b",
      "file": "live-repair-2026-10-05.json",
      "path": "model"
    },
    "totalTokens": {
      "value": 5066,
      "file": "live-repair-2026-10-05.json",
      "path": "attempts.0.usage.total_tokens"
    },
    "attempts": {
      "value": 1,
      "file": "live-repair-2026-10-05.json",
      "path": "attempts"
    }
  },
  "adapter": {
    "generated": {
      "value": 6,
      "file": "local-product-2026-10-05.json",
      "path": "live_adapter_generation.attempts"
    },
    "accepted": {
      "value": 0,
      "file": "local-product-2026-10-05.json",
      "path": "live_adapter_generation.accepted"
    },
    "activated": {
      "value": 0,
      "file": "local-product-2026-10-05.json",
      "path": "live_adapter_generation.activated"
    }
  }
} as const;

export type Evidence = typeof evidence;
